export const SET_TOTAL_SUM = 'SET_TOTAL_SUM';
// export const EDIT_FIELD = 'EDIT_FIELD';
// export const SWITCH_PAYMENT_TYPE = 'SWITCH_PAYMENT_TYPE';
// export const SWITCH_DATE_TYPE = 'SWITCH_DATE_TYPE';
// export const CALCULATE_MORTGAGE = 'CALCULATE_MORTGAGE';
// export const CLEAR_CALCULATION_RESULT = 'CLEAR_CALCULATION_RESULT';
